apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
    - name: cm-container
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
        - configMapRef:
            name: variables
